- hosts: all
  gather_facts: yes
  become: no
  vars_prompt:
    - name: pdfadmin_password
      prompt: pdfadmin password
      encrypt: "sha512_crypt"
      salt_size: 7
      private: yes
      confirm: yes
      when: pdfadmin_password == null
  tasks:
    - name: add group pdf
      become: yes
      group:
        name: pdf
        gid: 1001
        state: present

    - name: add user pdfadmin
      become: yes
      user:
        name: pdfadmin
        password: "{{ pdfadmin_password }}"
        uid: 1001
        group: pdf
        groups: 'adm'
        state: present

    - name: set up authorized_keys for the deploy user
      become: yes
      authorized_key: user=pdfadmin key="{{ lookup('file', './ssh/pdfadmin.pub') }}"

    - name: edit sudoers
      become: yes
      lineinfile:
        dest=/etc/sudoers
        state=present
        regexp="^pdfadmin ALL\=" line="pdfadmin ALL=(ALL) NOPASSWD:ALL"
        validate='visudo -cf %s'

