- hosts: all
  gather_facts: no           
  sudo: no
  vars:
    - sudoers_table:
        - who: pdfadmin
          where: ALL
          as_whom: (ALL)
          what: "NOPASSWD: ALL"
  tasks:
    # change: my_admin
    - name: set up authorized_keys for the deploy user
      authorized_key: user=pdfadmin key="{{ lookup('file', './ssh/my_admin.rsa.pub') }}"
    - name: edit sudoers
      become: yes
      lineinfile:
        dest=/etc/sudoers
        state=present
        regexp='^my_admin ALL\=' line='my_admin ALL=(ALL) NOPASSWD:ALL'
        validate='visudo -cf %s'
