- hosts: all
  become: no
  roles:
    - show_variables
    - hostname
    - sshd
    - ubuntu-basics

- hosts: cluster-master
  gather_facts: no
  become: no
  roles:
    - apt-mirror
    - dnsmasq
  vars:
    - dns_table:
      - nameserver: 8.8.8.8
      - nameserver: 8.8.4.4

- hosts: cluster-slave
  gather_facts: no
  become: no
  roles:
    - apt-mirror-client
  vars:
    my_apt_server: tristan.local
    
- hosts: th-work
  vars:
    hosts_table:
      - hostname: e2km1i.local
        ipv4_address: 192.168.100.11
        alias: e2km1i
      - hostname: rnas6.local
        ipv4_address: 192.168.100.12
        alias: rnas6
      - hostname: tristan.local
        ipv4_address: 192.168.100.20
        alias: tristan
      - hostname: walkure01.local
        ipv4_address: 192.168.100.21
        alias: walkure01
      - hostname: walkure02.local
        ipv4_address: 192.168.100.22
        alias: walkure02
      - hostname: walkure03.local
        ipv4_address: 192.168.100.23
        alias: walkure03
      - hostname: walkure04.local
        ipv4_address: 192.168.100.24
        alias: walkure04
      - hostname: walkure05.local
        ipv4_address: 192.168.100.25
        alias: walkure05
      - hostname: walkure06.local
        ipv4_address: 192.168.100.26
        alias: walkure06
      - hostname: walkure07.local
        ipv4_address: 192.168.100.27
        alias: walkure07
      - hostname: walkure08.local
        ipv4_address: 192.168.100.28
        alias: walkure08
  roles:
    - hosts
    - hostname

  
