- name: install devtools
  sudo: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - electric-fence
    - ddd
    - git
    - subversion
    - doxygen
    - graphviz
    - google-perftools
    - libgoogle-perftools-dev
