- name: install editor packages
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - vim
    - emacs
    - emacs-goodies-el
    - emacs-goodies-extra-el

  
