---
- name: install sysv-rc-conf
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - sysv-rc-conf
- include: ubuntu1404ja.yml
- include: shell.yml
- include: ntp.yml
- include: editor.yml
- include: devenv.yml
- include: devtools.yml
- include: python.yml
- include: gdb.yml
