- name: install devtools
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - python-dev 
    - python-setuptools
    - python-sphinx 
    - python-numpy 
    - python-matplotlib 
    - msgpack-python 
    - python-yaml 
    - pep8

